// USER TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

// PRODUCT TYPES
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_MY_PRODUCTS_SUCCESS = 'GET_MY_PRODUCTS_SUCCESS';

// ORDER TYPES
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_RECEIVED_ORDERS_SUCCESS = 'GET_RECEIVED_ORDERS_SUCCESS';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const PROCESS_ORDER_SUCCESS = 'PROCESS_ORDER_SUCCESS';

// CATEGORY TYPES
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';

// MESSAGE TYPES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// YARDSALE TYPES
export const GET_YARDSALE_SUCCESS = 'GET_YARDSALE_SUCCESS';
export const UPDATE_YARDSALE_SUCCESS = 'UPDATE_YARDSALE_SUCCESS';
