// USER TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

// PRODUCT TYPES
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_MY_PRODUCTS_SUCCESS = 'GET_MY_PRODUCTS_SUCCESS';

// ORDER TYPES
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';


// CATEGORY TYPES
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

// MESSAGE TYPES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// GATEGORY TYPES
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
