// USER TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

// PRODUCTS TYPES
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

// MESSAGE TYPES
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
